"""Shiki language and theme management for Anki Markdown.

Downloads language grammars and themes from esm.sh and manages them
in collection.media for mobile sync.
"""

from pathlib import Path
import urllib.request
import ssl
import json
import re

from aqt import mw

ADDON_DIR = Path(__file__).parent
ESM_BASE = "https://esm.sh/@shikijs"
SHIKI_VERSION = "3.20.0"

# Generated by scripts/generate.ts
AVAILABLE_LANGS = [
    "1c", "1c-query", "abap", "actionscript-3", "ada", "adoc", "angular-html",
    "angular-ts", "apache", "apex", "apl", "applescript", "ara", "asciidoc",
    "asm", "astro", "awk", "ballerina", "bash", "bat", "batch", "be",
    "beancount", "berry", "bibtex", "bicep", "blade", "bsl", "c", "c#", "c++",
    "cadence", "cairo", "cdc", "cjs", "clarity", "clj", "clojure",
    "closure-templates", "cmake", "cmd", "cobol", "codeowners", "codeql",
    "coffee", "coffeescript", "common-lisp", "console", "coq", "cpp", "cql",
    "crystal", "cs", "csharp", "css", "csv", "cts", "cue", "cypher", "d",
    "dart", "dax", "desktop", "diff", "docker", "dockerfile", "dotenv",
    "dream-maker", "edge", "elisp", "elixir", "elm", "emacs-lisp", "erb",
    "erl", "erlang", "f", "f#", "f03", "f08", "f18", "f77", "f90", "f95",
    "fennel", "fish", "fluent", "for", "fortran-fixed-form",
    "fortran-free-form", "fs", "fsharp", "fsl", "ftl", "gdresource",
    "gdscript", "gdshader", "genie", "gherkin", "git-commit", "git-rebase",
    "gjs", "gleam", "glimmer-js", "glimmer-ts", "glsl", "gnuplot", "go", "gql",
    "graphql", "groovy", "gts", "hack", "haml", "handlebars", "haskell",
    "haxe", "hbs", "hcl", "hjson", "hlsl", "hs", "html", "html-derivative",
    "http", "hurl", "hxml", "hy", "imba", "ini", "jade", "java", "javascript",
    "jinja", "jison", "jl", "js", "json", "json5", "jsonc", "jsonl", "jsonnet",
    "jssm", "jsx", "julia", "kdl", "kotlin", "kql", "kt", "kts", "kusto",
    "latex", "lean", "lean4", "less", "liquid", "lisp", "lit", "llvm", "log",
    "logo", "lua", "luau", "make", "makefile", "markdown", "marko", "matlab",
    "md", "mdc", "mdx", "mediawiki", "mermaid", "mips", "mipsasm", "mjs",
    "mmd", "mojo", "move", "mts", "nar", "narrat", "nextflow", "nf", "nginx",
    "nim", "nix", "nu", "nushell", "objc", "objective-c", "objective-cpp",
    "ocaml", "openscad", "pascal", "perl", "perl6", "php", "pkl", "plsql",
    "po", "polar", "postcss", "pot", "potx", "powerquery", "powershell",
    "prisma", "prolog", "properties", "proto", "protobuf", "ps", "ps1", "pug",
    "puppet", "purescript", "py", "python", "ql", "qml", "qmldir", "qss", "r",
    "racket", "raku", "razor", "rb", "reg", "regex", "regexp", "rel", "riscv",
    "rosmsg", "rs", "rst", "ruby", "rust", "sas", "sass", "scad", "scala",
    "scheme", "scss", "sdbl", "sh", "shader", "shaderlab", "shell",
    "shellscript", "shellsession", "smalltalk", "solidity", "soy", "sparql",
    "spl", "splunk", "sql", "ssh-config", "stata", "styl", "stylus", "svelte",
    "swift", "system-verilog", "systemd", "talon", "talonscript", "tasl",
    "tcl", "templ", "terraform", "tex", "tf", "tfvars", "toml", "ts",
    "ts-tags", "tsp", "tsv", "tsx", "turtle", "twig", "typ", "typescript",
    "typespec", "typst", "v", "vala", "vb", "verilog", "vhdl", "vim", "viml",
    "vimscript", "vue", "vue-html", "vue-vine", "vy", "vyper", "wasm",
    "wenyan", "wgsl", "wiki", "wikitext", "wit", "wl", "wolfram", "xml", "xsl",
    "yaml", "yml", "zenscript", "zig", "zsh", "文言",
]

AVAILABLE_THEMES = [
    "andromeeda", "aurora-x", "ayu-dark", "catppuccin-frappe",
    "catppuccin-latte", "catppuccin-macchiato", "catppuccin-mocha",
    "dark-plus", "dracula", "dracula-soft", "everforest-dark",
    "everforest-light", "github-dark", "github-dark-default",
    "github-dark-dimmed", "github-dark-high-contrast", "github-light",
    "github-light-default", "github-light-high-contrast", "gruvbox-dark-hard",
    "gruvbox-dark-medium", "gruvbox-dark-soft", "gruvbox-light-hard",
    "gruvbox-light-medium", "gruvbox-light-soft", "houston", "kanagawa-dragon",
    "kanagawa-lotus", "kanagawa-wave", "laserwave", "light-plus",
    "material-theme", "material-theme-darker", "material-theme-lighter",
    "material-theme-ocean", "material-theme-palenight", "min-dark",
    "min-light", "monokai", "night-owl", "nord", "one-dark-pro", "one-light",
    "plastic", "poimandres", "red", "rose-pine", "rose-pine-dawn",
    "rose-pine-moon", "slack-dark", "slack-ochin", "snazzy-light",
    "solarized-dark", "solarized-light", "synthwave-84", "tokyo-night",
    "vesper", "vitesse-black", "vitesse-dark", "vitesse-light",
]


def get_config() -> dict:
    """Get add-on config, falling back to defaults."""
    config = mw.addonManager.getConfig(__name__.split(".")[0])
    if config is None:
        config = {
            "languages": ["javascript", "typescript", "python", "html", "css", "json", "bash", "markdown", "glsl", "wgsl", "rust", "swift", "go"],
            "themes": {"light": "vitesse-light", "dark": "vitesse-dark"},
            "cardless": False,
        }
    return config


def esm_url(kind: str, name: str, version: str) -> str:
    """Generate esm.sh URL for a language or theme (bundled, self-contained)."""
    pkg = "langs" if kind == "lang" else "themes"
    # Use .bundle.mjs to get self-contained files with all dependencies inlined
    return f"{ESM_BASE}/{pkg}@{version}/es2022/{name}.bundle.mjs"


def fetch_module(url: str) -> bytes:
    """Fetch module content from esm.sh."""
    ctx = ssl.create_default_context()
    req = urllib.request.Request(url, headers={"User-Agent": "AnkiMarkdown/1.0"})
    with urllib.request.urlopen(req, timeout=30, context=ctx) as resp:
        return resp.read()


def is_alias_module(content: bytes) -> str | None:
    """Check if module is an alias (re-export from another module).
    Returns the canonical name if it's an alias, None otherwise.
    """
    text = content.decode("utf-8")
    # Alias modules are small and contain: import{default as o}from"../NAME.mjs"
    if len(text) < 200 and 'from"../' in text:
        match = re.search(r'from"\.\./([^.]+)\.mjs"', text)
        if match:
            return match.group(1)
    return None


def download_lang(name: str, version: str) -> Path:
    """Download a language grammar and save to add-on directory.

    Handles aliases by following the redirect to the canonical module.
    """
    url = esm_url("lang", name, version)
    content = fetch_module(url)

    # Check if this is an alias (e.g., bash -> shellscript)
    canonical = is_alias_module(content)
    if canonical:
        # Fetch the canonical module instead
        url = esm_url("lang", canonical, version)
        content = fetch_module(url)

    dest = ADDON_DIR / f"_lang-{name}.js"
    dest.write_bytes(content)
    return dest


def download_theme(name: str, version: str) -> Path:
    """Download a theme and save to add-on directory."""
    url = esm_url("theme", name, version)
    content = fetch_module(url)
    dest = ADDON_DIR / f"_theme-{name}.js"
    dest.write_bytes(content)
    return dest


def get_local_langs() -> set[str]:
    """Get set of language names that exist locally."""
    return {f.stem.replace("_lang-", "") for f in ADDON_DIR.glob("_lang-*.js")}


def get_local_themes() -> set[str]:
    """Get set of theme names that exist locally."""
    return {f.stem.replace("_theme-", "") for f in ADDON_DIR.glob("_theme-*.js")}


def cleanup_unused(config: dict) -> list[str]:
    """Remove language/theme files not in config. Returns list of removed files."""
    removed = []
    configured_langs = set(config.get("languages", []))
    configured_themes = {config["themes"]["light"], config["themes"]["dark"]}

    # Remove unused languages
    for f in ADDON_DIR.glob("_lang-*.js"):
        name = f.stem.replace("_lang-", "")
        if name not in configured_langs:
            f.unlink()
            removed.append(f.name)

    # Remove unused themes
    for f in ADDON_DIR.glob("_theme-*.js"):
        name = f.stem.replace("_theme-", "")
        if name not in configured_themes:
            f.unlink()
            removed.append(f.name)

    return removed


def sync_shiki_files() -> tuple[list[str], list[str]]:
    """Ensure all configured languages/themes exist locally.

    Returns (downloaded, errors) lists.
    """
    config = get_config()
    downloaded = []
    errors = []

    # Download missing languages
    local_langs = get_local_langs()
    for lang in config.get("languages", []):
        if lang not in local_langs:
            try:
                download_lang(lang, SHIKI_VERSION)
                downloaded.append(f"_lang-{lang}.js")
            except Exception as e:
                errors.append(f"Failed to download {lang}: {e}")

    # Download missing themes
    local_themes = get_local_themes()
    for theme in [config["themes"]["light"], config["themes"]["dark"]]:
        if theme not in local_themes:
            try:
                download_theme(theme, SHIKI_VERSION)
                downloaded.append(f"_theme-{theme}.js")
            except Exception as e:
                errors.append(f"Failed to download theme {theme}: {e}")

    return downloaded, errors


def generate_config_json() -> str:
    """Generate JSON config string for embedding in templates."""
    config = get_config()
    return json.dumps({
        "languages": config.get("languages", []),
        "themes": config.get("themes", {}),
        "cardless": config.get("cardless", False),
    }, separators=(",", ":"))
